### ISSUE TITLE
Spell Check quit on upgrade to 2.7

### ISSUE THREAD

**Issue by kenm393** [jendrikseipp/rednotebook#412]
### Versions

RedNotebook version (make sure you have the latest version): 

Operating system and version:

### Log output when reproducing behavior
($HOME/.rednotebook/rednotebook.log or C:\Users\<username>\.rednotebook.log)

**Comment by jendrikseipp** [comment]
Did you solve the issue? If not, could you please paste the contents of rednotebook.log (see above)?

**Comment by kenm393** [comment]
Here is the requested log:

2018-11-08 06:09:07,724 INFO     Writing log to file "/home/kenneth/.rednotebook/rednotebook.log"
2018-11-08 06:09:07,724 INFO     System encoding: utf-8
2018-11-08 06:09:07,724 INFO     Language code: en_US
2018-11-08 06:09:07,812 INFO     Running in portable mode: False
2018-11-08 06:09:07,812 INFO     First Start: False
2018-11-08 06:09:07,812 INFO     RedNotebook version: 2.7
2018-11-08 06:09:07,816 INFO     System info: machine: x86_64, platform: Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic, processor: x86_64, python_version: 3.6.6, release: 4.15.0-38-generic, system: Linux, GTK: (3, 22, 30), Glib: (2, 56, 1), PyGObject: (3, 26, 1), YAML: 3.12
2018-11-08 06:09:08,035 DEBUG    Default font: Noto Sans 14
2018-11-08 06:09:08,035 DEBUG    Default size: 14.0
2018-11-08 06:09:08,136 INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words', 'and', '#tags']
2018-11-08 06:09:08,136 INFO     Cloud include list: ['mtv', 'spam', 'work', 'job', 'play']
2018-11-08 06:09:08,136 DEBUG    Start compiling regexes
2018-11-08 06:09:08,137 DEBUG    Finished
2018-11-08 06:09:08,149 DEBUG    Tray icon visible: False
2018-11-08 06:09:08,150 INFO     Opening journal at '/home/kenneth/.rednotebook/data/Diary/Computer'
2018-11-08 06:09:08,151 DEBUG    Starting to load files in dir "/home/kenneth/.rednotebook/data/Diary/Computer"
2018-11-08 06:09:08,151 DEBUG    Loading file "/home/kenneth/.rednotebook/data/Diary/Computer/2018-10.txt"
2018-11-08 06:09:08,153 DEBUG    Loading file "/home/kenneth/.rednotebook/data/Diary/Computer/2018-11.txt"
2018-11-08 06:09:08,154 DEBUG    Finished loading files in dir "/home/kenneth/.rednotebook/data/Diary/Computer"
2018-11-08 06:09:08,172 DEBUG    Add mathjax code: False
2018-11-08 06:09:08,188 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Signals.SIGINT: 2>, <Signals.SIGQUIT: 3>, <Signals.SIGABRT: 6>, <Signals.SIGTERM: 15>, <Signals.SIGTSTP: 20>]
2018-11-08 06:09:08,188 DEBUG    Start took 0.37651896476745605 seconds
2018-11-08 06:09:08,188 DEBUG    Trying to enter the gtk main loop
2018-11-08 06:09:08,236 DEBUG    Update the cloud
2018-11-08 06:09:08,242 DEBUG    Cloud updated
2018-11-08 06:09:08,243 INFO     Last backup was made 3 days ago
2018-11-08 06:09:08,399 INFO     2.7 is the latest version
2018-11-08 06:09:08,400 INFO     Current version: 2.7, latest version: 2.7, newer: False
2018-11-08 06:12:08,506 DEBUG    Main frame destroyed
2018-11-08 06:12:08,516 INFO     Wrote file /home/kenneth/.rednotebook/data/Diary/Computer/2018-11.txt
2018-11-08 06:12:08,517 INFO     The content has been saved to /home/kenneth/.rednotebook/data/Diary/Computer
2018-11-08 06:12:08,517 INFO     The content has been saved to '/home/kenneth/.rednotebook/data/Diary/Computer'
2018-11-08 06:12:08,517 INFO     Goodbye!
2018-11-08 06:12:08,560 INFO     Peak memory: 118036932 KiB

**Comment by jendrikseipp** [comment]
Thanks! Could you please open RedNotebook, try to activate spell checking, close RedNotebook and paste the log again?

**Comment by kenm393** [comment]
Log with spell check enabled:
2018-11-08 12:35:04,463 INFO     Writing log to file "/home/kenneth/.rednotebook/rednotebook.log"
2018-11-08 12:35:04,463 INFO     System encoding: utf-8
2018-11-08 12:35:04,463 INFO     Language code: en_US
2018-11-08 12:35:04,557 INFO     Running in portable mode: False
2018-11-08 12:35:04,557 INFO     First Start: False
2018-11-08 12:35:04,557 INFO     RedNotebook version: 2.7
2018-11-08 12:35:04,561 INFO     System info: machine: x86_64, platform: Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic, processor: x86_64, python_version: 3.6.6, release: 4.15.0-38-generic, system: Linux, GTK: (3, 22, 30), Glib: (2, 56, 1), PyGObject: (3, 26, 1), YAML: 3.12
2018-11-08 12:35:04,788 DEBUG    Default font: Noto Sans 14
2018-11-08 12:35:04,788 DEBUG    Default size: 14.0
2018-11-08 12:35:04,889 INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words', 'and', '#tags']
2018-11-08 12:35:04,889 INFO     Cloud include list: ['mtv', 'spam', 'work', 'job', 'play']
2018-11-08 12:35:04,889 DEBUG    Start compiling regexes
2018-11-08 12:35:04,890 DEBUG    Finished
2018-11-08 12:35:04,902 DEBUG    Tray icon visible: False
2018-11-08 12:35:04,903 INFO     Opening journal at '/home/kenneth/.rednotebook/data/Diary/Computer'
2018-11-08 12:35:04,903 DEBUG    Starting to load files in dir "/home/kenneth/.rednotebook/data/Diary/Computer"
2018-11-08 12:35:04,904 DEBUG    Loading file "/home/kenneth/.rednotebook/data/Diary/Computer/2018-10.txt"
2018-11-08 12:35:04,907 DEBUG    Loading file "/home/kenneth/.rednotebook/data/Diary/Computer/2018-11.txt"
2018-11-08 12:35:04,908 DEBUG    Finished loading files in dir "/home/kenneth/.rednotebook/data/Diary/Computer"
2018-11-08 12:35:04,933 DEBUG    Add mathjax code: False
2018-11-08 12:35:04,949 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Signals.SIGINT: 2>, <Signals.SIGQUIT: 3>, <Signals.SIGABRT: 6>, <Signals.SIGTERM: 15>, <Signals.SIGTSTP: 20>]
2018-11-08 12:35:04,949 DEBUG    Start took 0.3926548957824707 seconds
2018-11-08 12:35:04,949 DEBUG    Trying to enter the gtk main loop
2018-11-08 12:35:05,000 DEBUG    Update the cloud
2018-11-08 12:35:05,004 DEBUG    Cloud updated
2018-11-08 12:35:05,006 INFO     Last backup was made 3 days ago
2018-11-08 12:35:05,222 INFO     2.7 is the latest version
2018-11-08 12:35:05,222 INFO     Current version: 2.7, latest version: 2.7, newer: False
2018-11-08 12:36:24,441 INFO     Wrote file /home/kenneth/.rednotebook/data/Diary/Computer/2018-11.txt
2018-11-08 12:36:24,441 INFO     The content has been saved to /home/kenneth/.rednotebook/data/Diary/Computer
2018-11-08 12:36:24,442 INFO     The content has been saved to '/home/kenneth/.rednotebook/data/Diary/Computer'
2018-11-08 12:36:24,442 INFO     Opening journal at '/home/kenneth/.rednotebook/data/Diary/My Day'
2018-11-08 12:36:24,442 DEBUG    Starting to load files in dir "/home/kenneth/.rednotebook/data/Diary/My Day"
2018-11-08 12:36:24,443 DEBUG    Loading file "/home/kenneth/.rednotebook/data/Diary/My Day/2018-10.txt"
2018-11-08 12:36:24,447 DEBUG    Loading file "/home/kenneth/.rednotebook/data/Diary/My Day/2018-11.txt"
2018-11-08 12:36:24,448 DEBUG    Finished loading files in dir "/home/kenneth/.rednotebook/data/Diary/My Day"
2018-11-08 12:36:24,450 DEBUG    Add mathjax code: False
2018-11-08 12:36:24,495 DEBUG    Update the cloud
2018-11-08 12:36:24,506 DEBUG    Cloud updated
2018-11-08 12:36:36,361 DEBUG    Main frame destroyed
2018-11-08 12:36:36,372 INFO     Wrote file /home/kenneth/.rednotebook/data/Diary/My Day/2018-11.txt
2018-11-08 12:36:36,372 INFO     The content has been saved to /home/kenneth/.rednotebook/data/Diary/My Day
2018-11-08 12:36:36,372 INFO     The content has been saved to '/home/kenneth/.rednotebook/data/Diary/My Day'
2018-11-08 12:36:36,373 INFO     Configuration has been saved to /home/kenneth/.rednotebook/configuration.cfg
2018-11-08 12:36:36,373 INFO     Goodbye!
2018-11-08 12:36:36,426 INFO     Peak memory: 134814152 KiB

**Comment by jendrikseipp** [comment]
From the log it seems that spell checking should be working. Are you sure spell checking is enabled? Have you tried misspelling a word? Can you right-click the misspelled word and get correction suggestions?

**Comment by kenm393** [comment]
Still not working and it is enabled, there are no suggestions listed. Now I noticed another and more serious problem. It seems that if I make and entry in a diary then move to another diary the first entry over writes the second entry, this makes RedNoteBook unusable since I keep 4 diary's. BTW: Spell checking works here and on other software. Do I need to create new diaries and if how do I import data?

**Comment by kenm393** [comment]
Just a thought, can I install the previous version?

**Comment by kenm393** [comment]
Installed 2.7 on Win10 and all is fine.

**Comment by jendrikseipp** [comment]
I tried to reproduce this on my system (Ubuntu 16.04). Here's what I found:

* Spell checking works if you enable it while RedNotebook is running (right-click makes suggestions)
* If spell checking is already selected when the application loads, spell checking does *not* work. Right-clicking gives the following warning: `gtk_text_buffer_set_mark: assertion 'gtk_text_iter_get_buffer (iter) == buffer' failed`.

**Comment by jendrikseipp** [comment]
Regarding the overwriting: could you please describe the exact steps for reproducing the error?

**Comment by kenm393** [comment]
On Thursday, November 8, 2018 5:12:04 PM CST Jendrik Seipp wrote:
> Regarding the overwriting: could you please describe the exact steps for
I am sure the problem was on my side. I  use gnome-encfs-manager to secure my 
directory and I think I upgraded while the directory was locked, hence the 
strange things. I completely removed the software and the .rednotebook 
directory, reinstalled and all is well. Thank you so much for looking at this 
for me, I am a bit red faced...
