### ISSUE TITLE
Preview button not working

### ISSUE THREAD

**Issue by jinkeanlim** [jendrikseipp/rednotebook#514]
I have been using Rednotebook since 2012 on Linux, Windows, and occasionally on Mac machines. I recently installed Rednotebook on macOS High Sierra followed the guides of pmgreen/rednotebook on macOS. 

One feature of Rednotebook, preview on browser, did not work on macOS High Sierra. I received this message in the terminal:

`Traceback (most recent call last):
  File "/Users/kjl/Documents/workspace/rednotebook/rednotebook/gui/main_window.py", line 446, in on_preview_button_clicked
    markup_string = markup.get_markup_for_day(self.day)
TypeError: get_markup_for_day() missing 1 required positional argument: 'target'`

Possible it is a bug? Could you please have a look?

**Comment by jendrikseipp** [comment]
You're in luck! I fixed this issue yesterday in version 2.20 :-)

Could you add a link to the instructions you used for macOS, please? Maybe they're helpful for others as well.

**Comment by jinkeanlim** [comment]
Dear Jendrik, 

Thanks for your prompt reply.

> You're in luck! I fixed this issue yesterday in version 2.20 :-)
> 

That’s cool. However, I am using version 2.20 and still having the same problem. The message saying that:

Traceback (most recent call last):
  File "/Users/jin/Documents/workspace/rednotebook/rednotebook/gui/main_window.py", line 446, in on_preview_button_clicked
    markup_string = markup.get_markup_for_day(self.day)
TypeError: get_markup_for_day() missing 1 required positional argument: 'target'

> Could you add a link to the instructions you used for macOS, please? Maybe they're helpful for others as well.
> 

Sure, sure. I followed the guide from the PM Green’s GitHub. Here you are the  URL:

https://gist.github.com/pmgreen/a1bf2c7015cb2a70d73e5e66bb84885e <https://gist.github.com/pmgreen/a1bf2c7015cb2a70d73e5e66bb84885e>

Thanks for your time.

Yours sincerely,
KJ Lim

**Comment by jendrikseipp** [comment]
Thanks for the link! It appears that you're still on an older version of RedNotebook though.

**Comment by jinkeanlim** [comment]
Dear Jendrik, 

You were right. I checked again and I was still on version 2.19. 

However, I downloaded rednotebook from source tarball and installed again. Still, the version is 2.19. 

If I executed with command .run from the source tarball, it is version 2.20.

That’s strange. 

Yours sincerely,
KJ LIM

**Comment by jendrikseipp** [comment]
Maybe the links on the website are cached.

**Comment by jinkeanlim** [comment]
Dear Jendrik, 

I found the source. I installed rednotebook in May at other directory and it was in the system path. Hence, it load previous installed rednotebook instead the latest one. 

Now, the problem solved.

Thanks.

Yours sincerely,
KJ LIM
